services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: defi-chatbot
    restart: unless-stopped
    env_file: .env
    volumes:
      # Volumen para persistir los datos del wallet
      - wallet-data:/app/data
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(1)"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    # Asegurar compatibilidad con Colima
    platform: linux/arm64
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'

volumes:
  wallet-data:
    name: defi-chatbot-wallet-data

networks:
  bot-network:
    name: defi-bot-network
    driver: bridge 